// PawNest demo catalogue. Every product has its own brand, description, specs, price and stock.
// Ratings/review counts here are only the *targets* used to generate sample reviews -
// the values shown in the shop are always calculated from the reviews collection.

const ANIMALS = [
  { slug: 'dogs', name: 'Dogs', icon: 'dog', description: 'Food, treats, grooming and gear for dogs and puppies.' },
  { slug: 'cats', name: 'Cats', icon: 'cat', description: 'Everything for cats and kittens.' },
  { slug: 'birds', name: 'Birds', icon: 'bird', description: 'Seed mixes, granules and cages for parrots, budgies and more.' },
  { slug: 'rabbits', name: 'Rabbits', icon: 'rabbit', description: 'Hay, pellets and accessories for rabbits.' },
  { slug: 'fish', name: 'Fish', icon: 'fish', description: 'Flakes, pellets and water care for aquariums.' },
  { slug: 'small-pets', name: 'Small Pets', icon: 'hamster', description: 'Hamsters, guinea pigs and other small companions.' },
];

const TYPES = [
  { slug: 'food', name: 'Food', icon: 'bowl', description: 'Complete daily nutrition, dry and wet.' },
  { slug: 'treats', name: 'Treats', icon: 'bone', description: 'Rewards and training treats.' },
  { slug: 'grooming', name: 'Grooming', icon: 'drop', description: 'Shampoos and coat care.' },
  { slug: 'accessories', name: 'Accessories', icon: 'collar', description: 'Collars, bowls, cages, litter and more.' },
  { slug: 'toys', name: 'Toys', icon: 'ball', description: 'Play, enrichment and exercise.' },
];

const P = (o) => o;

const PRODUCTS = [
  // ---------------------------------------------------------------- DOGS · FOOD
  P({ name: 'Royal Canin Medium Adult Dog Food', brand: 'Royal Canin', animals: ['dogs'], category: 'food', sub: 'Dry Food', shape: 'bag', tag: 'MEDIUM ADULT', weight: '3 kg', age: 'Adult', breed: 'All Breeds', price: 2800, disc: 12, stock: 50, rating: 4.8, reviews: 120, sold: 420, featured: true,
    desc: 'A complete and balanced food for medium breed dogs (11-25 kg) aged 1 to 7 years. Tailored kibble size and nutrients support strong bones, healthy skin and a coat that shines.',
    ing: 'Dehydrated poultry protein, rice, vegetable proteins, maize, animal fats, wheat, beet pulp, hydrolysed animal proteins, fish oil, minerals, yeast, vitamins.',
    ben: ['Supports strong bones and joints', 'Promotes healthy skin and a glossy coat', 'Optimal digestion with balanced fibre'],
    use: 'Feed 2 measured meals a day. A 15 kg dog needs about 190 g daily - adjust to activity level and always keep fresh water available.' }),
  P({ name: 'Royal Canin Maxi Adult Dog Food', brand: 'Royal Canin', animals: ['dogs'], category: 'food', sub: 'Dry Food', shape: 'bag', tag: 'MAXI ADULT', weight: '4 kg', age: 'Adult', breed: 'Large breeds (26-44 kg)', price: 4200, disc: 8, stock: 30, rating: 4.7, reviews: 64, sold: 190,
    desc: 'Designed for large breed dogs from 15 months old. Glucosamine and chondroitin help protect joints while the kibble shape encourages proper chewing.',
    ing: 'Dehydrated poultry protein, maize, rice, animal fats, vegetable protein isolate, beet pulp, fish oil, minerals, glucosamine, chondroitin, vitamins.',
    ben: ['Joint support for heavy frames', 'Kibble made for large jaws', 'Highly digestible proteins'],
    use: 'Feed 2 meals daily. A 35 kg dog typically needs 350-390 g per day; split into two portions.' }),
  P({ name: 'Royal Canin Mini Puppy Dry Dog Food', brand: 'Royal Canin', animals: ['dogs'], category: 'food', sub: 'Puppy Food', shape: 'bag', tag: 'MINI PUPPY', weight: '2 kg', age: 'Puppy (2-10 months)', breed: 'Small breeds (up to 10 kg)', price: 2300, disc: 10, stock: 42, rating: 4.6, reviews: 52, sold: 150,
    desc: 'Small, easy-to-chew kibble for puppies of small breeds during the crucial growth phase. Antioxidants help support natural defences.',
    ing: 'Dehydrated poultry protein, rice, maize, animal fats, vegetable protein isolate, hydrolysed animal protein, beet pulp, fish oil, minerals, vitamins.',
    ben: ['Supports natural defences', 'Small kibble for small mouths', 'Supports healthy digestion'],
    use: 'Feed 3-4 small meals a day up to 4 months, then 2-3 meals. Follow the weight chart on the pack.' }),
  P({ name: 'Royal Canin Golden Retriever Adult Dog Food', brand: 'Royal Canin', animals: ['dogs'], category: 'food', sub: 'Breed Specific', shape: 'bag', tag: 'GOLDEN RETRIEVER', weight: '3 kg', age: 'Adult', breed: 'Golden Retriever', price: 5900, disc: 0, stock: 12, rating: 4.9, reviews: 38, sold: 70, hidden: true,
    desc: 'Breed-specific nutrition for adult Golden Retrievers over 15 months. Formulated for the breed\'s coat, heart and tendency to gain weight.',
    ing: 'Rice, dehydrated poultry protein, maize flour, animal fats, vegetable protein isolate, fish oil, beet pulp, minerals, vitamins, marine algae.',
    ben: ['Supports coat and skin health', 'Heart health support with EPA & DHA', 'Helps maintain ideal weight'],
    use: 'Feed twice a day. A 30 kg Golden Retriever needs roughly 330 g daily.' }),
  P({ name: 'Pedigree Adult Beef & Vegetables Dry Dog Food', brand: 'Pedigree', animals: ['dogs'], category: 'food', sub: 'Dry Food', shape: 'bag', tag: 'ADULT BEEF', weight: '3 kg', age: 'Adult', breed: 'All Breeds', price: 2100, disc: 0, stock: 80, rating: 4.6, reviews: 86, sold: 380, featured: true,
    desc: 'Complete everyday food with real beef flavour, vegetables and cereals. Omega 6 and zinc help keep the skin healthy and the coat glossy.',
    ing: 'Cereals, meat and animal derivatives (beef min. 4%), vegetable protein extracts, oils and fats, vegetables (carrot min. 4%), minerals, vitamins.',
    ben: ['Complete and balanced daily nutrition', 'Omega 6 & zinc for skin and coat', 'Crunchy kibble helps reduce plaque'],
    use: 'Feed a 20 kg adult dog about 310 g per day, in two meals. Introduce gradually over 7 days.' }),
  P({ name: 'Pedigree Puppy Chicken & Milk Dry Dog Food', brand: 'Pedigree', animals: ['dogs'], category: 'food', sub: 'Puppy Food', shape: 'bag', tag: 'PUPPY CHICKEN', weight: '2.6 kg', age: 'Puppy (2-12 months)', breed: 'All Breeds', price: 1950, disc: 5, stock: 55, rating: 4.4, reviews: 41, sold: 160,
    desc: 'Soft-bite kibble with chicken and milk flavour for growing puppies, with calcium for strong teeth and bones.',
    ing: 'Cereals, meat and animal derivatives (chicken min. 4%), milk powder, oils and fats, vegetable protein extracts, minerals, vitamins.',
    ben: ['Calcium for teeth and bones', 'Supports healthy growth', 'Easy to chew and digest'],
    use: 'Puppies 2-4 months: 4 meals a day. 4-12 months: 2-3 meals a day. Moisten kibble with warm water for very young puppies.' }),
  P({ name: 'Pedigree Chicken Chunks in Gravy Wet Pouches (12 x 80 g)', brand: 'Pedigree', animals: ['dogs'], category: 'food', sub: 'Wet Food', shape: 'pouch', tag: 'CHICKEN GRAVY', weight: '12 x 80 g', age: 'Adult', breed: 'All Breeds', price: 2400, disc: 0, stock: 25, rating: 4.3, reviews: 27, sold: 90,
    desc: 'Tender chunks in rich gravy - a tasty topper for dry food or a full meal for small dogs.',
    ing: 'Meat and animal derivatives (chicken min. 4%), cereals, vegetable extracts, minerals, sugars.',
    ben: ['Extra moisture and flavour', 'Great for fussy eaters', 'Easy tear-open pouch'],
    use: 'Small dogs: 2-3 pouches a day as a complete meal. Larger dogs: mix one pouch with dry food.' }),
  P({ name: 'Purina Dog Chow Adult Chicken Dry Dog Food', brand: 'Purina', animals: ['dogs'], category: 'food', sub: 'Dry Food', shape: 'bag', tag: 'DOG CHOW', weight: '3 kg', age: 'Adult', breed: 'All Breeds', price: 2050, disc: 0, stock: 60, rating: 4.5, reviews: 73, sold: 300,
    desc: 'A dependable, complete daily diet with real chicken. Made with essential vitamins and minerals for strong bones and a healthy immune system.',
    ing: 'Cereals, meat and animal derivatives (chicken min. 4%), vegetable protein extracts, oils and fats, minerals, vitamins.',
    ben: ['Complete and balanced', 'Supports a healthy immune system', 'Good value for multi-dog homes'],
    use: 'Feed a 10 kg dog about 170 g per day divided into two meals.' }),
  P({ name: 'Purina Pro Plan Adult Sensitive Skin Salmon Dog Food', brand: 'Purina', animals: ['dogs'], category: 'food', sub: 'Dry Food', shape: 'bag', tag: 'PRO PLAN SALMON', weight: '3 kg', age: 'Adult', breed: 'Small & Medium breeds', price: 6400, disc: 5, stock: 18, rating: 4.8, reviews: 35, sold: 85,
    desc: 'Salmon-first recipe with live probiotics and omega-rich ingredients for dogs with sensitive skin and digestion.',
    ing: 'Salmon (30%), rice, wheat, corn gluten meal, animal fat, dried beet pulp, fish oil, live probiotics (Bifidobacterium longum), minerals, vitamins.',
    ben: ['Salmon is the first ingredient', 'Supports skin and digestive health', 'Live probiotics for gut balance'],
    use: 'Feed a 10 kg dog about 165 g per day. Transition over 7-10 days.' }),
  P({ name: "Hill's Science Diet Adult Chicken & Barley Dog Food", brand: "Hill's", animals: ['dogs'], category: 'food', sub: 'Dry Food', shape: 'bag', tag: 'SCIENCE DIET', weight: '2 kg', age: 'Adult', breed: 'All Breeds', price: 4900, disc: 0, stock: 22, rating: 4.7, reviews: 29, sold: 75,
    desc: 'Clinically proven antioxidant blend and high-quality protein for lean muscle and a healthy immune system in adult dogs.',
    ing: 'Chicken, cracked pearled barley, whole grain wheat, whole grain corn, corn gluten meal, chicken fat, chicken meal, soybean meal, lactic acid, flaxseed, vitamins, minerals.',
    ben: ['Supports lean muscle', 'Clinically proven antioxidants', 'Natural fibres for digestion'],
    use: 'A 20 kg dog needs about 300 g daily. Split into two meals.' }),

  // ---------------------------------------------------------------- DOGS · other
  P({ name: 'Pedigree Dentastix Daily Oral Care (Medium, 7 sticks)', brand: 'Pedigree', animals: ['dogs'], category: 'treats', sub: 'Dental Treats', shape: 'box', tag: 'DENTASTIX', weight: '180 g', age: 'Adult', breed: 'Medium (10-25 kg)', price: 720, disc: 0, stock: 90, rating: 4.5, reviews: 58, sold: 260,
    desc: 'A daily chew with a unique X-shape that reduces tartar build-up and freshens breath.',
    ing: 'Cereals, meat and animal derivatives, derivatives of vegetable origin, minerals, oils and fats.',
    ben: ['Reduces tartar build-up', 'Freshens breath', 'Dogs love the taste'],
    use: 'Give one stick a day to medium dogs (10-25 kg). Always supervise chewing and provide fresh water.' }),
  P({ name: 'PawNest Chicken Jerky Dog Treats', brand: 'PawNest', animals: ['dogs'], category: 'treats', sub: 'Training Treats', shape: 'bag-small', tag: 'CHICKEN JERKY', weight: '200 g', age: 'All ages', breed: 'All Breeds', price: 600, disc: 0, stock: 70, rating: 4.6, reviews: 44, sold: 210, featured: true,
    desc: 'Slow-dried chicken strips with no artificial colours - a high-value reward for training and good behaviour.',
    ing: 'Chicken breast (94%), vegetable glycerin, natural preservative (rosemary extract).',
    ben: ['Single-protein, easy to digest', 'Soft strips - break to any size', 'No artificial colours or flavours'],
    use: 'Give as a reward. Up to 5 strips per day for medium dogs; reduce main meals slightly.' }),
  P({ name: 'PawNest Care Oatmeal Dog Shampoo', brand: 'PawNest', animals: ['dogs'], category: 'grooming', sub: 'Shampoo', shape: 'bottle', tag: 'OATMEAL', weight: '500 ml', age: 'All ages', breed: 'All coats', price: 1300, disc: 0, stock: 35, rating: 4.5, reviews: 52, sold: 140,
    desc: 'Gentle soap-free shampoo with colloidal oatmeal and aloe to soothe dry, itchy skin and leave fur soft with a light fresh scent.',
    ing: 'Water, coco-glucoside, colloidal oatmeal, aloe vera extract, glycerin, panthenol, natural fragrance.',
    ben: ['Soothes dry, itchy skin', 'Soap-free and pH balanced for dogs', 'Leaves coat soft and easy to brush'],
    use: 'Wet the coat, massage in shampoo, leave for 2 minutes and rinse thoroughly. Avoid eyes. Use every 3-4 weeks.' }),
  P({ name: 'Beaphar Anti-Flea Dog Shampoo', brand: 'Beaphar', animals: ['dogs'], category: 'grooming', sub: 'Shampoo', shape: 'bottle', tag: 'ANTI-FLEA', weight: '250 ml', age: 'Adult dogs', breed: 'All coats', price: 1400, disc: 0, stock: 8, rating: 4.3, reviews: 19, sold: 55,
    desc: 'A medicated-style cleansing shampoo that helps keep fleas away while cleaning and conditioning the coat.',
    ing: 'Water, surfactants, natural neem and geraniol extracts, conditioning agents, fragrance.',
    ben: ['Helps deter fleas', 'Cleans and conditions', 'Pleasant, long-lasting scent'],
    use: 'Apply to a wet coat, lather and leave for 5 minutes before rinsing. Not for puppies under 12 weeks.' }),
  P({ name: 'PawNest Comfort Padded Dog Collar (Medium)', brand: 'PawNest', animals: ['dogs'], category: 'accessories', sub: 'Collars & Leashes', shape: 'collar', tag: 'PADDED COLLAR', weight: 'Medium (35-50 cm)', age: 'All ages', breed: 'Medium breeds', price: 850, disc: 0, stock: 100, rating: 4.5, reviews: 94, sold: 330, featured: true,
    desc: 'Soft neoprene-padded nylon collar with a quick-release buckle and a reflective stitch line for evening walks.',
    ing: 'Materials: nylon webbing, neoprene padding, zinc-alloy D-ring, plastic quick-release buckle.',
    ben: ['Padded to prevent rubbing', 'Reflective stitching for night walks', 'Adjustable fit with quick-release buckle'],
    use: 'Adjust so two fingers fit between collar and neck. Check the fit weekly on growing dogs.' }),
  P({ name: 'Trixie Premium Nylon Dog Leash (1.2 m)', brand: 'Trixie', animals: ['dogs'], category: 'accessories', sub: 'Collars & Leashes', shape: 'leash', tag: 'NYLON LEASH', weight: '1.2 m x 20 mm', age: 'All ages', breed: 'Medium & Large', price: 1150, disc: 0, stock: 45, rating: 4.4, reviews: 31, sold: 95,
    desc: 'Strong, hand-friendly nylon leash with a sturdy swivel clip that stops tangling.',
    ing: 'Materials: woven nylon, stainless-steel swivel snap hook.',
    ben: ['Comfortable grip loop', 'Swivel clip prevents twisting', 'Machine washable'],
    use: 'Suitable for dogs up to 40 kg. Inspect the stitching and clip regularly.' }),
  P({ name: 'Trixie Stainless Steel Pet Bowl', brand: 'Trixie', animals: ['dogs', 'cats'], category: 'accessories', sub: 'Bowls & Feeders', shape: 'bowl', tag: 'STEEL BOWL', weight: '900 ml', age: 'All ages', breed: 'All Breeds', price: 850, disc: 0, stock: 60, rating: 4.4, reviews: 36, sold: 125,
    desc: 'Non-slip stainless steel bowl with a rubber base - hygienic, dishwasher-safe and built to last.',
    ing: 'Materials: 18/8 stainless steel, non-slip rubber base.',
    ben: ['Rust-resistant stainless steel', 'Rubber ring stops sliding', 'Dishwasher safe'],
    use: 'Wash after every meal. Use for dry food, wet food or water.' }),
  P({ name: 'Kong Classic Dog Toy (Medium)', brand: 'Kong', animals: ['dogs'], category: 'toys', sub: 'Chew Toys', shape: 'kong', tag: 'CLASSIC', weight: 'Medium', age: 'Adult', breed: 'Dogs 7-16 kg', price: 2900, disc: 0, stock: 14, rating: 4.9, reviews: 47, sold: 60,
    desc: 'The famous natural-rubber chew toy with an unpredictable bounce. Stuff it with treats to keep dogs busy and happy.',
    ing: 'Materials: durable natural red rubber.',
    ben: ['Extra-tough rubber for chewers', 'Stuffable for mental enrichment', 'Erratic bounce for fetch'],
    use: 'Stuff with treats or paste and freeze for longer play. Replace if damaged. Always supervise.' }),
  P({ name: 'Trixie Cotton Rope Tug Toy', brand: 'Trixie', animals: ['dogs'], category: 'toys', sub: 'Tug Toys', shape: 'rope', tag: 'ROPE TUG', weight: '40 cm', age: 'All ages', breed: 'All Breeds', price: 650, disc: 0, stock: 0, rating: 4.2, reviews: 16, sold: 88,
    desc: 'Knotted cotton rope for tug games, fetch and gentle teeth cleaning.',
    ing: 'Materials: braided cotton fibres.',
    ben: ['Great for interactive play', 'Cotton fibres help clean teeth', 'Washable'],
    use: 'Play tug gently and supervise; discard when frayed.' }),

  // ---------------------------------------------------------------- CATS
  P({ name: 'Royal Canin Persian Adult Cat Food', brand: 'Royal Canin', animals: ['cats'], category: 'food', sub: 'Dry Food', shape: 'bag', tag: 'PERSIAN', weight: '2 kg', age: 'Adult (12 months+)', breed: 'Persian', price: 2800, disc: 0, stock: 40, rating: 4.8, reviews: 110, sold: 360, featured: true,
    desc: 'Almond-shaped kibble designed for the flat face of Persian cats, with nutrients to support a long, dense coat and reduce hairballs.',
    ing: 'Dehydrated poultry protein, rice, maize flour, animal fats, vegetable protein isolate, beet pulp, fish oil, minerals, psyllium, vitamins.',
    ben: ['Kibble shaped for flat faces', 'Supports a long, healthy coat', 'Helps hairball elimination'],
    use: 'A 4 kg cat needs about 55 g per day. Divide into 2-3 meals and provide fresh water.' }),
  P({ name: 'Royal Canin Kitten Second Age Dry Food', brand: 'Royal Canin', animals: ['cats'], category: 'food', sub: 'Kitten Food', shape: 'bag', tag: 'KITTEN', weight: '2 kg', age: 'Kitten (4-12 months)', breed: 'All Breeds', price: 3400, disc: 5, stock: 28, rating: 4.7, reviews: 46, sold: 130,
    desc: 'Supports natural defences and healthy growth for kittens from 4 to 12 months.',
    ing: 'Dehydrated poultry protein, rice, animal fats, maize gluten, wheat flour, vegetable fibres, hydrolysed animal proteins, fish oil, minerals, vitamins.',
    ben: ['Supports immune system', 'High-energy growth nutrition', 'Small kibble for kitten teeth'],
    use: '3 meals a day until 6 months, then 2 meals. A 3 kg kitten needs about 60 g daily.' }),
  P({ name: 'Royal Canin Indoor Adult Cat Food', brand: 'Royal Canin', animals: ['cats'], category: 'food', sub: 'Dry Food', shape: 'bag', tag: 'INDOOR 27', weight: '2 kg', age: 'Adult (1-7 years)', breed: 'All Breeds', price: 3300, disc: 0, stock: 33, rating: 4.6, reviews: 39, sold: 120,
    desc: 'Lower calories and moderate fat for less active indoor cats, with fibres that reduce stool odour.',
    ing: 'Dehydrated poultry protein, rice, wheat gluten, maize, vegetable fibres, animal fats, beet pulp, hydrolysed proteins, minerals, vitamins.',
    ben: ['Helps maintain ideal weight', 'Reduces litter box odour', 'Supports hairball control'],
    use: 'A 4 kg indoor cat needs about 45 g per day. Weigh out portions.' }),
  P({ name: 'Whiskas Tuna Adult Dry Cat Food', brand: 'Whiskas', animals: ['cats'], category: 'food', sub: 'Dry Food', shape: 'bag', tag: 'TUNA', weight: '1.2 kg', age: 'Adult (1+ years)', breed: 'All Breeds', price: 2450, disc: 0, stock: 75, rating: 4.7, reviews: 95, sold: 350, featured: true,
    desc: 'Crunchy, tuna-flavoured kibble with 41 nutrients for a complete daily diet that keeps cats active and their coats shiny.',
    ing: 'Cereals, meat and animal derivatives, fish and fish derivatives (tuna min. 4%), vegetable protein extracts, oils and fats, minerals, vitamins, taurine.',
    ben: ['Complete and balanced nutrition', 'Tuna taste cats love', 'Supports healthy skin and coat'],
    use: 'A 4 kg cat needs about 60 g daily. Mix with wet food for variety.' }),
  P({ name: 'Whiskas Junior Mackerel Dry Cat Food', brand: 'Whiskas', animals: ['cats'], category: 'food', sub: 'Kitten Food', shape: 'bag', tag: 'JUNIOR MACKEREL', weight: '1.1 kg', age: 'Kitten (2-12 months)', breed: 'All Breeds', price: 1750, disc: 0, stock: 48, rating: 4.5, reviews: 33, sold: 115,
    desc: 'Kitten-sized crunchy kibble with mackerel and milk, rich in calcium for strong bones and teeth.',
    ing: 'Cereals, meat and animal derivatives, fish and fish derivatives (mackerel min. 4%), milk derivatives, vegetable protein extracts, minerals, vitamins.',
    ben: ['Calcium for growing bones', 'Small kibble', 'Real milk goodness'],
    use: 'Feed kittens 2-12 months 40-70 g per day, in 3-4 portions.' }),
  P({ name: 'Whiskas Mackerel in Jelly Wet Pouches (12 x 85 g)', brand: 'Whiskas', animals: ['cats'], category: 'food', sub: 'Wet Food', shape: 'pouch', tag: 'MACKEREL JELLY', weight: '12 x 85 g', age: 'Adult', breed: 'All Breeds', price: 2400, disc: 0, stock: 25, rating: 4.4, reviews: 28, sold: 100,
    desc: 'Soft fish pieces in jelly that boost hydration and make every mealtime exciting.',
    ing: 'Meat and animal derivatives, fish and fish derivatives (mackerel min. 4%), minerals, sugars, vitamins.',
    ben: ['Extra hydration', 'Easy-open pouch', 'Perfect topper for dry food'],
    use: 'Feed 3-4 pouches daily for an adult 4 kg cat, or 1 pouch with dry food.' }),
  P({ name: 'Me-O Ocean Fish Adult Dry Cat Food', brand: 'Me-O', animals: ['cats'], category: 'food', sub: 'Dry Food', shape: 'bag', tag: 'OCEAN FISH', weight: '1 kg', age: 'Adult', breed: 'All Breeds', price: 1200, disc: 0, stock: 90, rating: 4.5, reviews: 67, sold: 310,
    desc: 'Affordable ocean-fish flavoured kibble with taurine for eye and heart health in adult cats.',
    ing: 'Cereals, meat and bone meal, fish meal, soybean meal, animal fat, taurine, vitamins, minerals.',
    ben: ['Taurine supports eyes and heart', 'Omega-rich fish flavour', 'Great everyday value'],
    use: 'Feed a 4 kg cat about 55 g a day, in two meals.' }),
  P({ name: 'Me-O Kitten Mackerel Dry Cat Food', brand: 'Me-O', animals: ['cats'], category: 'food', sub: 'Kitten Food', shape: 'bag', tag: 'KITTEN MACKEREL', weight: '1.1 kg', age: 'Kitten (1-12 months)', breed: 'All Breeds', price: 1500, disc: 0, stock: 36, rating: 4.3, reviews: 24, sold: 80,
    desc: 'Mackerel-flavoured food for growing kittens, with DHA to support brain and vision development.',
    ing: 'Cereals, meat and bone meal, fish meal, soybean meal, animal fat, DHA, taurine, vitamins, minerals.',
    ben: ['DHA for brain development', 'Bite-size kibble', 'Balanced for growth'],
    use: 'Feed 45-65 g per day for kittens up to 6 months, spread over 3 meals.' }),
  P({ name: 'Me-O Delite Tuna in Jelly Pouches (12 x 80 g)', brand: 'Me-O', animals: ['cats'], category: 'food', sub: 'Wet Food', shape: 'pouch', tag: 'DELITE TUNA', weight: '12 x 80 g', age: 'Adult', breed: 'All Breeds', price: 1900, disc: 0, stock: 30, rating: 4.2, reviews: 18, sold: 60,
    desc: 'Whole tuna flakes in clear jelly - a light, tasty wet meal or a treat mixed with kibble.',
    ing: 'Tuna (min. 45%), fish extract, gelling agent, vitamins, minerals.',
    ben: ['High moisture content', 'Real tuna flakes', 'Easy-open pouch'],
    use: 'Feed 2-3 pouches a day alongside dry food; refrigerate opened pouches.' }),
  P({ name: "Hill's Science Diet Adult Cat Food Chicken Recipe", brand: "Hill's", animals: ['cats'], category: 'food', sub: 'Dry Food', shape: 'bag', tag: 'SCIENCE DIET', weight: '1.5 kg', age: 'Adult', breed: 'All Breeds', price: 2600, disc: 0, stock: 26, rating: 4.6, reviews: 61, sold: 140, featured: true,
    desc: 'Vet-recommended nutrition with high-quality protein for lean muscle and an antioxidant blend for a healthy immune system.',
    ing: 'Chicken, brewers rice, corn gluten meal, whole grain wheat, chicken fat, chicken liver flavour, pork fat, flaxseed, vitamins, minerals, taurine.',
    ben: ['Supports lean muscle', 'Healthy immune system', 'Supports urinary health'],
    use: 'A 4 kg cat needs roughly 60 g daily; split into 2 meals.' }),
  P({ name: 'Me-O Creamy Cat Treats Tuna (4 sticks)', brand: 'Me-O', animals: ['cats'], category: 'treats', sub: 'Creamy Treats', shape: 'box', tag: 'CREAMY TUNA', weight: '4 x 15 g', age: 'All ages', breed: 'All Breeds', price: 360, disc: 0, stock: 120, rating: 4.6, reviews: 57, sold: 270,
    desc: 'Lickable creamy treats that cats find irresistible - ideal for bonding, medicine time and rewards.',
    ing: 'Tuna, fish extract, tuna oil, thickener, vitamins, taurine.',
    ben: ['Silky and easy to lick', 'Made with real tuna', 'Great for bonding'],
    use: 'Up to 2 sticks per day for adult cats. Tear the tip and let your cat lick.' }),
  P({ name: 'Beaphar Kitten & Cat Shampoo', brand: 'Beaphar', animals: ['cats'], category: 'grooming', sub: 'Shampoo', shape: 'bottle', tag: 'CAT SHAMPOO', weight: '200 ml', age: 'Kitten & Adult', breed: 'All coats', price: 1300, disc: 0, stock: 24, rating: 4.5, reviews: 40, sold: 90,
    desc: 'Mild, tear-free shampoo with a soft fragrance made for the sensitive skin and fine coats of cats and kittens.',
    ing: 'Water, mild surfactants, glycerin, chamomile extract, panthenol, fragrance.',
    ben: ['Gentle on sensitive skin', 'Leaves fur soft and shiny', 'Suitable from 8 weeks'],
    use: 'Wet the coat with lukewarm water, lather gently and rinse thoroughly. Keep away from eyes and ears.' }),
  P({ name: 'Me-O Lemon Clumping Cat Litter', brand: 'Me-O', animals: ['cats'], category: 'accessories', sub: 'Litter', shape: 'bag', tag: 'LEMON LITTER', weight: '10 L', age: 'All ages', breed: 'All cats', price: 1600, disc: 0, stock: 40, rating: 4.4, reviews: 35, sold: 150,
    desc: 'Fast-clumping bentonite litter with a fresh lemon scent that locks in odours and is easy to scoop.',
    ing: 'Materials: natural bentonite clay, lemon fragrance.',
    ben: ['Clumps in seconds', 'Neutralises odours', 'Low dust'],
    use: 'Fill the tray with 5-7 cm of litter. Scoop daily and replace fully every 2 weeks.' }),
  P({ name: 'Trixie Sisal Cat Scratching Post (60 cm)', brand: 'Trixie', animals: ['cats'], category: 'accessories', sub: 'Scratchers', shape: 'post', tag: 'SCRATCH POST', weight: '60 cm', age: 'All ages', breed: 'All cats', price: 3900, disc: 0, stock: 10, rating: 4.7, reviews: 22, sold: 45,
    desc: 'Sturdy scratching post wrapped in natural sisal, with a wide, stable base and a plush top perch.',
    ing: 'Materials: natural sisal rope, plush fabric, particle-board base.',
    ben: ['Protects your furniture', 'Stable heavy base', 'Comfy perch on top'],
    use: 'Place near where your cat sleeps or by the furniture they scratch. Rub with catnip to attract.' }),
  P({ name: 'Trixie Feather Wand Cat Toy', brand: 'Trixie', animals: ['cats'], category: 'toys', sub: 'Interactive Toys', shape: 'wand', tag: 'FEATHER WAND', weight: '45 cm', age: 'All ages', breed: 'All cats', price: 700, disc: 0, stock: 65, rating: 4.5, reviews: 30, sold: 120,
    desc: 'A flexible wand with a bundle of natural feathers and a jingle bell to spark your cat\'s hunting instinct.',
    ing: 'Materials: wooden handle, natural feathers, metal bell, elastic cord.',
    ben: ['Encourages exercise', 'Strengthens the human-cat bond', 'Natural feathers cats adore'],
    use: 'Wave and drag the feathers like prey. Store out of reach after play.' }),

  // ---------------------------------------------------------------- BIRDS
  P({ name: 'Versele-Laga Prestige Budgies Seed Mix', brand: 'Versele-Laga', animals: ['birds'], category: 'food', sub: 'Seed Mix', shape: 'bag', tag: 'PRESTIGE BUDGIES', weight: '1 kg', age: 'Adult', breed: 'Budgerigars', price: 1600, disc: 0, stock: 44, rating: 4.6, reviews: 38, sold: 140, featured: true,
    desc: 'A varied mix of seeds and millets balanced for budgerigars, with added vitamins and minerals for bright plumage.',
    ing: 'Canary seed, white millet, red millet, oats, niger seed, linseed, sunflower seed, vitamin and mineral supplement.',
    ben: ['Varied seeds encourage natural foraging', 'Supports feather colour', 'Dust-controlled'],
    use: 'Offer about a tablespoon a day per bird, plus fresh water and greens. Discard husks daily.' }),
  P({ name: 'Versele-Laga Prestige Premium Parrots Mix', brand: 'Versele-Laga', animals: ['birds'], category: 'food', sub: 'Seed Mix', shape: 'bag', tag: 'PRESTIGE PARROTS', weight: '1 kg', age: 'Adult', breed: 'Medium & large parrots', price: 2900, disc: 0, stock: 26, rating: 4.7, reviews: 26, sold: 70,
    desc: 'A rich blend of nuts, seeds, fruits and pellets to satisfy the varied appetite of parrots.',
    ing: 'Sunflower seed, peanuts, safflower, oats, dried fruit, corn, peas, pellets, vitamins, minerals.',
    ben: ['Nuts and fruit for enrichment', 'Balanced for larger parrots', 'Supports vitality'],
    use: 'Feed 30-50 g per parrot per day; supplement with vegetables.' }),
  P({ name: 'Vitakraft Menu Vital Budgies Food', brand: 'Vitakraft', animals: ['birds'], category: 'food', sub: 'Seed Mix', shape: 'bag', tag: 'MENU VITAL', weight: '1 kg', age: 'Adult', breed: 'Budgerigars', price: 1500, disc: 0, stock: 52, rating: 4.5, reviews: 34, sold: 125,
    desc: 'Complete budgie food with Vital-Vitamin blend and extra-fine seeds for strong immunity and glossy feathers.',
    ing: 'Cereals, seeds, vegetable by-products, minerals, vitamins (A, D3, E), amino acids.',
    ben: ['Vitamin-fortified', 'Supports immunity', 'Made from selected seeds'],
    use: 'Offer a level tablespoon per bird daily and refresh the dish every morning.' }),
  P({ name: 'Vitakraft Menu Vital Cockatiel Food', brand: 'Vitakraft', animals: ['birds'], category: 'food', sub: 'Seed Mix', shape: 'bag', tag: 'COCKATIEL', weight: '900 g', age: 'Adult', breed: 'Cockatiels', price: 1700, disc: 0, stock: 38, rating: 4.4, reviews: 21, sold: 66,
    desc: 'A tasty mix of sunflower, millet and grain with a vitamin boost for cockatiels and similar medium parakeets.',
    ing: 'Cereals, seeds, sunflower kernels, vegetable by-products, minerals, vitamins.',
    ben: ['Tailored to cockatiels', 'Rich in energy for active birds', 'Vitamin fortified'],
    use: 'Feed roughly 2 tablespoons per bird each day with fresh greens.' }),
  P({ name: 'Hagen Tropican Parrot Granules', brand: 'Hagen', animals: ['birds'], category: 'food', sub: 'Pellets', shape: 'bag', tag: 'TROPICAN', weight: '820 g', age: 'Adult', breed: 'Parrots', price: 3800, disc: 6, stock: 20, rating: 4.8, reviews: 30, sold: 60,
    desc: 'Nutritionally complete granules that stop selective feeding - every bite delivers the same balanced nutrition.',
    ing: 'Corn, wheat, soy, oat groats, peanuts, canola oil, vitamins, minerals, amino acids.',
    ben: ['Complete nutrition in every bite', 'Reduces selective feeding', 'No artificial colours'],
    use: 'Offer as the main diet with fresh vegetables. Change water daily.' }),
  P({ name: 'Hagen Tropican Lifetime Cockatiel Granules', brand: 'Hagen', animals: ['birds'], category: 'food', sub: 'Pellets', shape: 'bag', tag: 'COCKATIEL', weight: '820 g', age: 'Adult', breed: 'Cockatiels', price: 3400, disc: 0, stock: 17, rating: 4.6, reviews: 19, sold: 45,
    desc: 'Lifetime maintenance granules formulated for cockatiels and lovebirds.',
    ing: 'Corn, wheat, oat groats, soy, canola oil, sunflower, vitamins, minerals, amino acids.',
    ben: ['Formulated for cockatiels', 'Supports feather quality', 'Easy to digest'],
    use: 'Give 1-2 tablespoons per bird per day; transition slowly from seed.' }),
  P({ name: 'Vitakraft Kracker Honey Budgie Treat (2 sticks)', brand: 'Vitakraft', animals: ['birds'], category: 'treats', sub: 'Treat Sticks', shape: 'box', tag: 'KRACKER HONEY', weight: '2 x 30 g', age: 'All ages', breed: 'Budgies', price: 350, disc: 0, stock: 85, rating: 4.5, reviews: 27, sold: 160,
    desc: 'Seed-and-honey treat sticks to hang in the cage - fun to nibble and good for beak care.',
    ing: 'Seeds, cereals, honey, vegetable by-products.',
    ben: ['Keeps birds busy', 'Beak-friendly texture', 'Attaches easily to bars'],
    use: 'Hang one stick in the cage and replace when finished. Offer as a treat, not a meal.' }),
  P({ name: 'Ferplast Piano Bird Cage (Small)', brand: 'Ferplast', animals: ['birds'], category: 'accessories', sub: 'Cages & Habitats', shape: 'cage', tag: 'PIANO CAGE', weight: '46 x 29 x 47 cm', age: 'All ages', breed: 'Budgies, canaries', price: 4800, disc: 0, stock: 9, rating: 4.4, reviews: 14, sold: 25,
    desc: 'A roomy powder-coated cage with two perches, feeders and a removable tray for quick cleaning.',
    ing: 'Materials: powder-coated steel wire, ABS plastic tray and feeders.',
    ben: ['Easy-clean sliding tray', 'Includes perches and feeders', 'Rust-resistant coating'],
    use: 'Place away from draughts and direct sun. Clean the tray daily.' }),
  P({ name: 'Hagen Living World Wooden Bird Swing', brand: 'Hagen', animals: ['birds'], category: 'toys', sub: 'Swings & Perches', shape: 'swing', tag: 'WOOD SWING', weight: 'Small', age: 'All ages', breed: 'Budgies, finches', price: 650, disc: 0, stock: 33, rating: 4.3, reviews: 11, sold: 40,
    desc: 'Natural wood swing that gives small birds a place to play, perch and exercise.',
    ing: 'Materials: natural untreated wood, stainless-steel hanger.',
    ben: ['Encourages exercise', 'Natural wood is gentle on feet', 'Easy to hang'],
    use: 'Hang inside the cage away from feeders so droppings do not soil it.' }),

  // ---------------------------------------------------------------- RABBITS
  P({ name: 'Versele-Laga Cuni Complete Adult Rabbit Food', brand: 'Versele-Laga', animals: ['rabbits'], category: 'food', sub: 'Pellets', shape: 'bag', tag: 'CUNI COMPLETE', weight: '1.75 kg', age: 'Adult', breed: 'All rabbits', price: 1650, disc: 0, stock: 34, rating: 4.6, reviews: 26, sold: 90,
    desc: 'Extruded pellets with high fibre content and Yucca for a healthy gut and less smelly droppings.',
    ing: 'Grass meal, alfalfa, wheat bran, sunflower meal, beet pulp, linseed, yucca extract, vitamins, minerals.',
    ben: ['High fibre for digestion', 'Yucca reduces odour', 'No selective feeding'],
    use: 'Feed a small bowl daily (about 30 g per kg body weight) alongside unlimited hay.' }),
  P({ name: 'Vitakraft Menu Vital Rabbit Food', brand: 'Vitakraft', animals: ['rabbits'], category: 'food', sub: 'Seed Mix', shape: 'bag', tag: 'MENU VITAL', weight: '1 kg', age: 'Adult', breed: 'All rabbits', price: 1300, disc: 0, stock: 41, rating: 4.4, reviews: 22, sold: 75,
    desc: 'Crunchy mix of grains, vegetables and herbs, enriched with vitamins for daily wellbeing.',
    ing: 'Cereals, vegetable by-products, alfalfa, peas, carrot flakes, herbs, minerals, vitamins.',
    ben: ['Variety of textures', 'Vitamin enriched', 'Supports dental wear'],
    use: 'Give a tablespoon per kg body weight each day plus hay.' }),
  P({ name: 'Oxbow Western Timothy Hay', brand: 'Oxbow', animals: ['rabbits', 'small-pets'], category: 'food', sub: 'Hay', shape: 'hay', tag: 'TIMOTHY HAY', weight: '1 kg', age: 'All ages', breed: 'Rabbits, guinea pigs', price: 2200, disc: 5, stock: 28, rating: 4.8, reviews: 33, sold: 110,
    desc: 'Fresh, sweet-smelling second-cut timothy hay - the foundation of a healthy diet for rabbits and guinea pigs.',
    ing: '100% sun-cured Western timothy hay.',
    ben: ['Essential fibre for digestion', 'Wears down continuously growing teeth', 'Dust-controlled'],
    use: 'Provide unlimited fresh hay every day; it should be at least 80% of the diet.' }),
  P({ name: 'Trixie Rabbit Water Bottle', brand: 'Trixie', animals: ['rabbits', 'small-pets'], category: 'accessories', sub: 'Bowls & Feeders', shape: 'waterbottle', tag: 'WATER BOTTLE', weight: '500 ml', age: 'All ages', breed: 'Rabbits, guinea pigs', price: 800, disc: 0, stock: 47, rating: 4.3, reviews: 17, sold: 55,
    desc: 'Drip-free bottle with a stainless-steel spout and a strong metal holder.',
    ing: 'Materials: BPA-free plastic, stainless-steel spout, metal bracket.',
    ben: ['Drip-proof spout', 'Keeps water clean', 'Easy to refill'],
    use: 'Clip to the cage, check that water flows daily and refill with fresh water.' }),

  // ---------------------------------------------------------------- FISH
  P({ name: 'Tetra TetraMin Tropical Flakes', brand: 'Tetra', animals: ['fish'], category: 'food', sub: 'Flakes', shape: 'tub', tag: 'TETRAMIN', weight: '100 g', age: 'All ages', breed: 'Tropical fish', price: 950, disc: 0, stock: 60, rating: 4.7, reviews: 45, sold: 190, featured: true,
    desc: 'The classic complete flake food for all tropical fish, with ProCare for vitality and clear water.',
    ing: 'Fish and fish by-products, cereals, yeast extracts, algae, vegetable by-products, vitamins, minerals.',
    ben: ['Complete nutrition for tropical fish', 'Clear-water formula', 'Supports colour and vitality'],
    use: 'Feed small amounts 1-2 times a day, only what fish eat in 2 minutes.' }),
  P({ name: 'Hikari Goldfish Gold Floating Pellets', brand: 'Hikari', animals: ['fish'], category: 'food', sub: 'Pellets', shape: 'tub', tag: 'GOLDFISH GOLD', weight: '100 g', age: 'All ages', breed: 'Goldfish, koi', price: 1100, disc: 0, stock: 32, rating: 4.6, reviews: 21, sold: 70,
    desc: 'Easy-to-digest floating pellets with wheat germ for goldfish, reducing waste and boosting colour.',
    ing: 'Fish meal, wheat flour, wheat germ meal, spirulina, krill, vitamins, stabilised vitamin C.',
    ben: ['Wheat germ aids digestion', 'Enhances natural colour', 'Reduces waste'],
    use: 'Feed 2-3 times a day in an amount eaten within 3 minutes.' }),
  P({ name: 'Sera Vipan Flakes', brand: 'Sera', animals: ['fish'], category: 'food', sub: 'Flakes', shape: 'tub', tag: 'VIPAN', weight: '100 ml', age: 'All ages', breed: 'Tropical fish', price: 1200, disc: 0, stock: 27, rating: 4.5, reviews: 18, sold: 55,
    desc: 'Nutrient-rich flakes made with gentle drying to keep vitamins intact; good for community tanks.',
    ing: 'Fish meal, wheat flour, algae, yeast, krill, vitamins, minerals.',
    ben: ['Gentle production keeps nutrients', 'Suitable for community tanks', 'Low water pollution'],
    use: 'Feed a pinch several times a day.' }),
  P({ name: 'Tetra AquaSafe Water Conditioner', brand: 'Tetra', animals: ['fish'], category: 'accessories', sub: 'Water Care', shape: 'bottle', tag: 'AQUASAFE', weight: '250 ml', age: 'All ages', breed: 'Freshwater aquariums', price: 1600, disc: 0, stock: 21, rating: 4.6, reviews: 25, sold: 65,
    desc: 'Makes tap water safe for fish immediately by neutralising chlorine and heavy metals, while adding protective vitamins.',
    ing: 'Water conditioning agents, vitamins, aloe vera extract.',
    ben: ['Neutralises chlorine and chloramine', 'Protects fish slime coat', 'Works instantly'],
    use: 'Add 5 ml per 10 litres of new water each time you fill or change the aquarium.' }),

  // ---------------------------------------------------------------- SMALL PETS
  P({ name: 'Versele-Laga Prestige Hamsters Mix', brand: 'Versele-Laga', animals: ['small-pets'], category: 'food', sub: 'Seed Mix', shape: 'bag', tag: 'PRESTIGE HAMSTER', weight: '500 g', age: 'Adult', breed: 'Hamsters', price: 1250, disc: 0, stock: 36, rating: 4.5, reviews: 20, sold: 60,
    desc: 'A crunchy blend of seeds, grains and dried vegetables that encourages natural foraging behaviour.',
    ing: 'Cereals, seeds, dried vegetables, sunflower seed, peanuts, mealworms, vitamins, minerals.',
    ben: ['Encourages foraging', 'Varied textures', 'Rich in protein'],
    use: 'Feed one to two tablespoons daily and remove old fresh food.' }),
  P({ name: 'Vitakraft Menu Vital Guinea Pig Food', brand: 'Vitakraft', animals: ['small-pets'], category: 'food', sub: 'Pellets', shape: 'bag', tag: 'GUINEA PIG', weight: '1 kg', age: 'Adult', breed: 'Guinea pigs', price: 1400, disc: 0, stock: 29, rating: 4.4, reviews: 19, sold: 52,
    desc: 'Vitamin C-stabilised mix with herbs and vegetable flakes for daily guinea pig care.',
    ing: 'Grass meal, alfalfa, wheat, vegetable flakes, herbs, stabilised vitamin C, minerals.',
    ben: ['Stabilised vitamin C', 'High-fibre for digestion', 'Herbal variety'],
    use: 'Offer a level tablespoon per day with unlimited hay and fresh vegetables.' }),
  P({ name: 'Oxbow Essentials Adult Guinea Pig Food', brand: 'Oxbow', animals: ['small-pets'], category: 'food', sub: 'Pellets', shape: 'bag', tag: 'CAVY CUISINE', weight: '2.25 kg', age: 'Adult', breed: 'Guinea pigs', price: 3900, disc: 0, stock: 15, rating: 4.8, reviews: 27, sold: 48,
    desc: 'Uniform timothy-based pellets with stabilised vitamin C and no seeds or dried fruit, so guinea pigs cannot pick and choose.',
    ing: 'Timothy grass meal, soybean hulls, wheat middlings, soybean meal, stabilised vitamin C, prebiotics, minerals.',
    ben: ['Uniform pellets prevent picking', 'Timothy-based for digestion', 'Added vitamin C'],
    use: 'Feed 1/8 cup per day per guinea pig alongside unlimited hay.' }),
  P({ name: 'Trixie Silent Hamster Exercise Wheel', brand: 'Trixie', animals: ['small-pets'], category: 'toys', sub: 'Exercise', shape: 'wheel', tag: 'SILENT WHEEL', weight: '20 cm', age: 'All ages', breed: 'Hamsters', price: 1800, disc: 0, stock: 19, rating: 4.2, reviews: 13, sold: 30,
    desc: 'A quiet, solid-surface wheel that protects tiny feet and lets hamsters run all night without squeaking.',
    ing: 'Materials: BPA-free plastic, metal ball-bearing axle.',
    ben: ['Ultra-quiet spinning', 'Solid running surface', 'Fits most cages'],
    use: 'Attach securely inside the cage and clean weekly with mild soap.' }),

  // ---------------------------------------------------------------- Multi-pet grooming
  P({ name: 'PawNest Care Gentle Pet Shampoo', brand: 'PawNest', animals: ['dogs', 'cats'], category: 'grooming', sub: 'Shampoo', shape: 'bottle', tag: 'GENTLE SHAMPOO', weight: '250 ml', age: 'All ages', breed: 'All coats', price: 850, disc: 0, stock: 80, rating: 4.6, reviews: 84, sold: 290, featured: true,
    desc: 'An everyday gentle shampoo with chamomile and aloe that cleans without stripping natural oils, suitable for both dogs and cats.',
    ing: 'Water, coco-glucoside, glycerin, chamomile extract, aloe vera, panthenol, natural fragrance.',
    ben: ['Suitable for dogs and cats', 'Chamomile & aloe soothe skin', 'Rinses out easily'],
    use: 'Massage into a wet coat, leave for a minute and rinse until water runs clear. Avoid eyes.' }),
];

module.exports = { ANIMALS, TYPES, PRODUCTS };
